[package]
name = "sol-gate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["sqlite"]
sqlite = ["sqlx/sqlite"]
postgres = ["sqlx/postgres"]

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
platform-dirs = "0.3"
clap = { version = "3.0", features = ["derive"] }
itertools = "0.9.0"
sha2 = "~0.10.0"
hex = {version = "0.4", features=["serde"]}
sqlx = { version = "0.6", features = [ "runtime-tokio-native-tls", "offline", "migrate"] } 
include_dir = "0.7"
reqwest= "0.11"
axum = "0.5"
mime_guess = "2.0"
tower = {version = "0.4"}
tower-http = {version = "0.3", features = ["add-extension", "auth", "compression-gzip", "trace"]}
open = "3.0"
simple-error = "0.2.3"


[profile.release]
debug = 1
